// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Vercel/Supabase uses POSTGRES_PRISMA_URL for pooling
    url: (globalThis as any).process?.env?.POSTGRES_PRISMA_URL || (globalThis as any).process?.env?.DATABASE_URL,
  },
});
